import './globals.css';
import {Inter} from 'next/font/google';
import {ReactNode} from 'react';
import Providers from './components/Providers';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IProps {
  children: ReactNode;
}

export default function RootLayout({children}: IProps) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
