import './globals.css';
import {Inter} from 'next/font/google';
import {ReactNode} from 'react';
import Providers from './components/Providers';
import Navbar from './components/Navbar';
import {ToastComponent} from './components/ToastComponent';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IProps {
  children: ReactNode;
}

export default function RootLayout({children}: IProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center`}>
        <Providers>
          <Navbar />
          {children}
          <ToastComponent />
        </Providers>
      </body>
    </html>
  );
}
